_target_: src.lightning_modules.FRDSB

forward_model:
  _target_: src.networks.unets.UNet2D
  sample_size: [32, 32]
  in_channels: 3
  out_channels: 3
  layers_per_block: 2
  down_block_types: ["DownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D"]
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D"] # remember to change this (use attention)
  block_out_channels: [64, 128, 256]
  dropout: 0.0

backward_model:
  _target_: src.networks.unets.UNet2D
  sample_size: [32, 32]
  in_channels: 3
  out_channels: 3
  layers_per_block: 2
  down_block_types: ["DownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D"]
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D"] # remember to change this (use attention)
  block_out_channels: [64, 128, 256]
  dropout: 0.0

max_gamma: 0.01
min_gamma: 0.01
num_steps: 100
patience: 10
strict_gammas: True
max_norm: 1
initial_forward_sampling: "ornstein_uhlenbeck"