_target_: src.lightning_modules.FRDSB

forward_model:
  _target_: src.networks.unets.UNet2D
  sample_size: [32, 32]
  in_channels: 3
  out_channels: 3
  layers_per_block: 2
  down_block_types: ["DownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D"]
  up_block_types: ["AttnUpBlock2D", "AttnUpBlock2D", "UpBlock2D"]
  block_out_channels: [64, 128, 256]
  dropout: 0.0

backward_model:
  _target_: src.networks.unets.UNet2D
  sample_size: [32, 32]
  in_channels: 3
  out_channels: 3
  layers_per_block: 2
  down_block_types: ["DownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D"]
  up_block_types: ["AttnUpBlock2D", "AttnUpBlock2D", "UpBlock2D"]
  block_out_channels: [64, 128, 256]
  dropout: 0.0

patience: 10
max_norm: 1