_target_: src.lightning_modules.schrodinger_bridge.FRSchrodingerBridge

forward_model:
  _target_: src.networks.simple_models.FFNWithTimeEncoding
  in_features: 5
  out_features: 5
  num_layers: 4
  hidden_size: 256
  time_encoding_size: 64

backward_model:
  _target_: src.networks.simple_models.FFNWithTimeEncoding
  in_features: 5
  out_features: 5
  num_layers: 4
  hidden_size: 256
  time_encoding_size: 64

patience: 5
max_gamma: 0.01
min_gamma: 0.01
num_steps: 100
lr: 0.0001