_target_: src.lightning_modules.reparameterized_dsb.FRDSB

forward_model:
  _target_: src.networks.ResMLP
  dim_in: 10
  dim_out: 10
  dim_hidden: 128
  num_layers: 3
  n_cond: 101

backward_model:
  _target_: src.networks.ResMLP
  dim_in: 10
  dim_out: 10
  dim_hidden: 128
  num_layers: 3
  n_cond: 101

max_gamma: 0.01
min_gamma: 0.01
num_steps: 100
max_iterations: 1000
lr: 0.001
lr_factor: 0.5
lr_patience: 5
max_norm: 1