_target_: src.lightning_modules.TRDSB

forward_model:
  _target_: src.networks.unets.UNet2D
  sample_size: [16, 16]
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D"]
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D"]
  block_out_channels: [32, 32, 32]
  dropout: 0.1

backward_model:
  _target_: src.networks.unets.UNet2D
  sample_size: [16, 16]
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D"]
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D"]
  block_out_channels: [32, 32, 32]
  dropout: 0.1

patience: 5
max_iterations: 20000