_target_: src.lightning_modules.vae.SimpleVAE

encoder:
  _target_: src.networks.basetorchmodule.PretrainedModel
  module:
    _target_: src.networks.encoders_decoders.SimpleEncoderForImages
    height: 28
    width: 28
    channels: 1
    out_features: 5
  experiment_id: 'd137eec64f2849899f607c83881c2874'
  old_model_keyword: 'encoder'

decoder:
  _target_: src.networks.basetorchmodule.PretrainedModel
  module:
    _target_: src.networks.encoders_decoders.SimpleDecoderForImages
    height: 28
    width: 28
    channels: 1
    in_features: 5
  experiment_id: 'd137eec64f2849899f607c83881c2874'
  old_model_keyword: 'decoder'

beta: 1.0