_target_: src.lightning_modules.reparameterized_dsb.TRDSB

forward_model:
  _target_: src.networks.simple_models.SimpleNetwork
  in_features: 2
  out_features: 2
  encoder_layers: [128, 128]
  decoder_layers: [256, 256, 256]
  time_encoding_size: 32

backward_model:
  _target_: src.networks.simple_models.SimpleNetwork
  in_features: 2
  out_features: 2
  encoder_layers: [128, 128]
  decoder_layers: [256, 256, 256]
  time_encoding_size: 32

patience: 6
max_gamma: 0.01
min_gamma: 0.01
num_steps: 100
lr: 0.00001