_target_: src.lightning_modules.schrodinger_bridge.FRSchrodingerBridge

forward_model:
  _target_: src.networks.simple_models.SimpleNetwork
  in_features: 2
  out_features: 2
  encoder_layers: [32, 32]
  decoder_layers: [128, 128, 128]
  time_encoding_size: 16

backward_model:
  _target_: src.networks.simple_models.SimpleNetwork
  in_features: 2
  out_features: 2
  encoder_layers: [32, 32]
  decoder_layers: [128, 128, 128]
  time_encoding_size: 16

patience: 20
max_gamma: 0.1
min_gamma: 0.01
num_steps: 19
lr: 0.0001