_target_: src.lightning_modules.schrodinger_bridge.FRSchrodingerBridge

forward_model:
  _target_: diffusers.UNet2DModel
  sample_size: [32, 32]
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  down_block_types: ["DownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D"]
  up_block_types: ["AttnUpBlock2D", "AttnUpBlock2D", "AttnUpBlock2D", "UpBlock2D"] # remember to change this (use attention)
  block_out_channels: [32, 64, 128, 256]
  dropout: 0.2

backward_model:
  _target_: diffusers.UNet2DModel
  sample_size: [32, 32]
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  down_block_types: ["DownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D"]
  up_block_types: ["AttnUpBlock2D", "AttnUpBlock2D", "AttnUpBlock2D", "UpBlock2D"]
  block_out_channels: [32, 64, 128, 256]
  dropout: 0.2

patience: 5
max_gamma: 0.01
min_gamma: 0.01
num_steps: 100
lr: 0.01