_target_: src.lightning_modules.reparameterized_dsb.TRDSB

forward_model:
  _target_: src.networks.simple_models.SimpleNetwork
  in_features: 2
  out_features: 2
  num_time_embeddings: 101
  encoder_layers: [32, 64, 128]
  decoder_layers: [128, 256, 32]
  time_encoding_size: 32

backward_model:
  _target_: src.networks.simple_models.SimpleNetwork
  in_features: 2
  out_features: 2
  num_time_embeddings: 101
  encoder_layers: [32, 64, 128]
  decoder_layers: [128, 256, 32]
  time_encoding_size: 32

max_gamma: 0.1
min_gamma: 0.1
num_steps: 10
max_iterations: 50_000
strict_gammas: True
lr: 0.001
lr_factor: 0.5
lr_patience: 5
max_norm: 1
initial_forward_sampling: "ornstein_uhlenbeck"