_target_: src.lightning_modules.TRDSB

forward_model:
  _target_: src.networks.unets.UNet2D
  sample_size: [16, 16]
  in_channels: 1
  out_channels: 1
  layers_per_block: 1
  down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D"]
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D"] # remember to change this (use attention)
  block_out_channels: [32, 32, 32]
  dropout: 0.2

backward_model:
  _target_: src.networks.unets.UNet2D
  sample_size: [16, 16]
  in_channels: 1
  out_channels: 1
  layers_per_block: 1
  down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D"]
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D"]
  block_out_channels: [32, 32, 32]
  dropout: 0.2

max_gamma: 0.1
min_gamma: 0.1
num_steps: 10
max_iterations: 6000
strict_gammas: True
lr: 0.001
lr_factor: 0.5
lr_patience: 5
max_norm: 1
initial_forward_sampling: "ornstein_uhlenbeck"