_target_: src.lightning_modules.schrodinger_bridge.TRSchrodingerBridge

forward_model:
  _target_: src.networks.unets.UNet2D
  sample_size: [32, 32]
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D"]
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D"] # remember to change this (use attention)
  block_out_channels: [32, 64, 128]
  dropout: 0.2

backward_model:
  _target_: src.networks.unets.UNet2D
  sample_size: [32, 32]
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D"]
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D"] # remember to change this (use attention)
  block_out_channels: [32, 64, 128]
  dropout: 0.2

patience: 50
max_gamma: 0.1
min_gamma: 0.1
num_steps: 10
lr: 0.001