_target_: src.lightning_modules.schrodinger_bridge.FRSchrodingerBridge

forward_model:
  _target_: src.networks.unets.Unet2D
  sample_size: [32, 32]
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D"]
  block_out_channels: [32, 32, 64, 128]
  dropout: 0.1

backward_model:
  _target_: src.networks.unets.Unet2D
  sample_size: [32, 32]
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D"]
  block_out_channels: [32, 32, 64, 128]
  dropout: 0.1

patience: 5
max_gamma: 0.01
min_gamma: 0.01
num_steps: 100
lr: 0.0001