_target_: src.lightning_modules.vae.SimpleVAE

encoder:
  _target_: src.networks.encoders_decoders.SimpleEncoderForImages
  height: 28
  width: 28
  channels: 1
  out_features: 5

decoder:
  _target_: src.networks.encoders_decoders.SimpleDecoderForImages
  height: 28
  width: 28
  channels: 1
  in_features: 5

beta: 1.0