_target_: src.lightning_modules.vae.SimpleVAE

encoder:
  _target_: src.networks.encoders_decoders.ImageEncoder
  height: 32
  width: 32
  channels: 1
  latent_dim: 10
  channels_list: [8, 16, 32, 64, 128]

decoder:
  _target_: src.networks.encoders_decoders.ImageDecoder
  height: 32
  width: 32
  channels: 1
  latent_dim: 10
  channels_list: [8, 16, 32, 64, 128]

beta: 1.0