_target_: src.lightning_modules.reparameterized_dsb.FRDSB

forward_model:
  _target_: src.networks.ResMLP
  dim_in: 2
  dim_out: 2
  dim_hidden: 256
  num_layers: 3
  n_cond: 101

backward_model:
  _target_: src.networks.ResMLP
  dim_in: 2
  dim_out: 2
  dim_hidden: 256
  num_layers: 3
  n_cond: 101

max_gamma: 0.1
min_gamma: 0.1
num_steps: 10
max_iterations: 50_000
strict_gammas: True
lr: 0.001
lr_factor: 0.5
lr_patience: 5
max_norm: 1