_target_: src.lightning_modules.schrodinger_bridge.FRSchrodingerBridge

forward_model:
  _target_: src.networks.unets.UNet0D
  in_features: 2
  out_features: 2
  num_layers: 2

backward_model:
  _target_: src.networks.unets.UNet0D
  in_features: 2
  out_features: 2
  num_layers: 2

patience: 5
max_gamma: 0.01
min_gamma: 0.01
num_steps: 100
lr: 0.01