_target_: src.lightning_modules.schrodinger_bridge.FRSchrodingerBridge

forward_model:
  _target_: src.networks.simple_models.FFNWithTimeEncoding
  in_features: 2
  out_features: 2
  time_encoding_size: 64

backward_model:
  _target_: src.networks.simple_models.FFNWithTimeEncoding
  in_features: 2
  out_features: 2
  time_encoding_size: 64

max_gamma: 0.001
min_gamma: 0.0001