_target_: src.lightning_modules.vae.SimpleVAE

encoder:
  _target_: src.networks.encoders_decoders.SimpleEncoderForImages
  height : 32
  width : 32
  channels : 1
  out_features : 16
  hidden_layer_size : 1024

decoder:
  _target_: src.networks.encoders_decoders.SimpleDecoderForImages
  height : 32
  width : 32
  channels : 1
  in_features : 16
  hidden_layer_size : 1024

beta: 0.1