_target_: src.lightning_modules.reparameterized_dsb.TRDSBWithHack

forward_model:
  _target_: src.networks.simple_models.SimpleNetwork
  in_features: 2
  out_features: 2
  encoder_layers: [32, 32]
  decoder_layers: [128, 128, 128]
  time_encoding_size: 16

backward_model:
  _target_: src.networks.simple_models.SimpleNetwork
  in_features: 2
  out_features: 2
  encoder_layers: [32, 32]
  decoder_layers: [128, 128, 128]
  time_encoding_size: 16

patience: 6
max_gamma: 0.01
min_gamma: 0.01
num_steps: 100
lr: 0.0001