_target_: src.lightning_modules.reparameterized_dsb.FRDSB

forward_model:
  _target_: src.networks.ResMLP
  dim_in: 2
  dim_out: 2
  dim_hidden: 128
  num_layers: 3
  n_cond: 101

backward_model:
  _target_: src.networks.ResMLP
  dim_in: 2
  dim_out: 2
  dim_hidden: 128
  num_layers: 3
  n_cond: 101

max_iterations: 5000
max_norm: 1

optimizer:
  _target_: torch.optim.Adam
  _partial_: True
  lr: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: True
  mode: 'min'
  factor: 0.5
  patience: 5