_target_: src.lightning_modules.FRDSB

forward_model:
  _target_: src.networks.ResMLP
  dim_in: 2
  dim_out: 2
  dim_hidden: 128
  num_layers: 3
  n_cond: 101

backward_model:
  _target_: src.networks.ResMLP
  dim_in: 2
  dim_out: 2
  dim_hidden: 128
  num_layers: 3
  n_cond: 101